/* ============================================================
   BUCH 2, KAPITEL 2.6–3.1 (Seiten 48–63)
   Sauspiel als gerufener Spieler / als Gegenspieler.

   Die Hände sind so abgetippt, wie sie im Buch abgedruckt sind. Das
   Buch legt sie immer gleich aus — Trümpfe absteigend, dann Eichel,
   Gras, Schellen, jede Farbe von der Sau abwärts. Das ist dieselbe
   Sortierung wie sortHand() in der Engine, und test/buchstellungen.js
   prüft sie: passt die Reihenfolge nicht, wurde eine Karte falsch
   abgelesen.

   REGELN   = die Merksätze, in eigenen Worten zusammengefasst.
   STELLUNGEN = die abgebildeten Blätter, als Übungsaufgaben.
              Die Lösung ist die des Buches, nicht die der Engine —
              wo das Buch spricht, hat das Buch recht.
   ============================================================ */

export const REGELN = [
  {
    id: "freie-farbe-anzeigen",
    kapitel: "2.6",
    seite: 49,
    titel: "Dem Partner die freie Farbe anzeigen",
    kurz: "Als gerufener Partner spiele ich statt Trumpf die dritte Farbe an — das zeigt, welche Farbe ich frei bin.",
    lang:
      "Nach dem Suchen der Rufsau weiß jeder, wer zusammenspielt. Habe ich nur wenige kleine Trümpfe, hilft Trumpf ziehen dem Spielmacher wenig. Spiele ich stattdessen die dritte Farbe an — also weder Trumpf noch Ruffarbe —, sagt das dem Spielmacher unmissverständlich: die vierte Farbe bin ich frei, dort kann ich einstechen.",
  },
  {
    id: "nicht-immer-hoechster-trumpf",
    kapitel: "2.7",
    seite: 51,
    titel: "Nicht immer den höchsten Trumpf anspielen",
    kurz: "Sitzt der Spielmacher in Mittelhand, spiele ich als Partner meinen höchsten Trumpf nur mit einem der drei großen Ober an.",
    lang:
      "Die Faustregel „höchsten Trumpf zuerst\" gilt so nicht. Sitzt der Spielmacher in Mittelhand, bringt ein hoher, aber nicht großer Trumpf ihn in Schwierigkeiten: er muss übernehmen und verbraucht dafür einen Ober, oder er lässt den Stich der Hinterhand. Mit einem kleinen Trumpf anzuspielen lässt ihm die Wahl und der Hinterhand keine Chance zu schmieren.",
  },
  {
    id: "ohne-trumpf-rufsau-spielen",
    kapitel: "2.8",
    seite: 53,
    titel: "Ohne Trumpf die Rufsau ausspielen",
    kurz: "Habe ich als gerufener Partner keinen Trumpf, gebe ich mich schnell zu erkennen — nötigenfalls mit der Rufsau selbst.",
    lang:
      "Normalerweise zeigt man sich durch Ausspielen eines Trumpfs als Partner. Ohne Trumpf und ohne die vier Ruffarbkarten zum Davonlaufen bleibt nur, die Rufsau selbst zu spielen. Dass sie dabei oft gestochen wird, darf nicht abschrecken: viel teurer ist ein Spielmacher, der bis zum sechsten Stich nicht weiß, dass sein Partner trumpflos ist.",
  },
  {
    id: "nicht-davonlaufen-nach-abspatzen",
    kapitel: "2.9",
    seite: 55,
    titel: "Nicht davonlaufen, wenn der Spielmacher abspatzt",
    kurz: "Wirft der Spielmacher eine Lusche der Ruffarbe ab, statt auf einer freien Farbe einzustechen, spiele ich Trumpf statt davonzulaufen.",
    lang:
      "Das Abspatzen verrät, dass er die Ruffarbe loswerden will und dort nichts zu holen ist. Davonlaufen würde ihm genau die Gelegenheit verschaffen, die er sucht. Trumpf zu spielen nimmt den Gegnern dagegen die Möglichkeit, meine Ruffarbe abzustechen.",
  },
  {
    id: "nach-spritze-rollen-tauschen",
    kapitel: "2.10",
    seite: 57,
    titel: "Nach einer Spritze die Rollen tauschen",
    kurz: "Nach einer Spritze verhalte ich mich als Spieler eher wie ein Nichtspieler und als Nichtspieler eher wie ein Spieler.",
    lang:
      "Wer spritzt, sagt damit: ich bin trumpfstark und habe ein gutes Beiblatt. Die Gegenpartei hat damit faktisch die Spielmacherrolle übernommen. Als Spielerpartei spiele ich deshalb keinen Trumpf mehr, sondern versuche mein Glück in den Farben, am liebsten mit einer blanken Karte.",
  },
  {
    id: "vorausdenken-ausspiel",
    kapitel: "2.11",
    seite: 59,
    titel: "Vorausdenken: wer soll wann am Ausspiel sein?",
    kurz: "Bei mehreren Möglichkeiten entscheidet, wer nach dem Stich am Ausspiel ist — notfalls übersteche ich den eigenen Partner.",
    lang:
      "Den eigenen Partner zu überstechen sieht falsch aus und ist manchmal genau richtig: nämlich dann, wenn ich anschließend selbst anspielen will und der Partner sonst in eine Farbe läuft, die mir schadet. Ich denke deshalb nicht nur an diesen Stich, sondern daran, wer den nächsten eröffnet.",
  },
  {
    id: "blanke-zehn-suchen",
    kapitel: "3.1",
    seite: 63,
    titel: "Suchen mit einer blanken Zehn",
    kurz: "Es gibt keinen triftigen Grund, auf das Suchen der Rufsau mit einer blanken Zehn zu verzichten.",
    lang:
      "Die Zehn geht dabei oft verloren — aber die Wahrscheinlichkeit, dass der Partner in der Ruffarbe einzeln steht, ist gering, und ohne Suchen weiß ich lange nicht, wer wo sitzt. Je weniger Karten der gerufenen Farbe ich habe, desto unwahrscheinlicher ist es, dass der Spielmacher dort frei ist.",
  },
  {
    id: "dreifach-besetzte-zehn",
    kapitel: "3.2",
    seite: 65,
    titel: "Suchen mit einer dreifach besetzten Farbe",
    kurz: "Mit einer dreifach besetzten Zehn suche ich nur, wenn mir sonst noch Schmierkarten bleiben.",
    lang:
      "Habe ich drei Karten der Ruffarbe, ist die Chance gut, dass der Spielmacher dort frei ist und einsticht. Die Zehn wäre dann verloren. Der König tut denselben Dienst und kostet weniger. Je weniger Schmierkarten mir sonst bleiben, desto eher behalte ich die Zehn für die sicheren Stiche des Partners.",
  },
  {
    id: "nicht-suchen-ohne-partnertrumpf",
    kapitel: "3.3",
    seite: 67,
    titel: "Nicht suchen, wenn der Partner keinen Trumpf hat",
    kurz: "Steht fest, dass mein Partner trumpflos ist, verzichte ich in der Regel auf das Suchen der Rufsau.",
    lang:
      "Suchen lohnt nur, wenn der Partner einstechen oder die Sau später überstechen kann. Ist er offensichtlich trumpflos, verschenke ich meine Karte der Ruffarbe an die Spielerpartei und verrate obendrein meine eigene Lage. Dann spiele ich lieber eine Farbe, in der ich selbst noch etwas werden kann.",
  },
  {
    id: "anspiel-farbe-ohne-sau",
    kapitel: "3.4",
    seite: 69,
    titel: "Anspielen bei freier Ruffarbe",
    kurz: "Habe ich keine Karte der Ruffarbe, spiele ich zuerst eine Farbe an, von der ich keine Sau habe.",
    lang:
      "Als Gegenspieler will ich die Rufsau stechen — dafür muss die Ruffarbe gespielt werden, und ich selbst kann sie nicht bringen. Also gebe ich das Ausspiel weiter: eine Farbe, in der ich keine Sau halte, kostet mich wenig und signalisiert dem Mitspieler, dass ich dort nichts habe. Meine eigene Sau spiele ich nicht an, die will ich später selbst einbringen.",
  },
  {
    id: "spritze-voraussetzung",
    kapitel: "3.5",
    seite: 71,
    titel: "Voraussetzung für eine Spritze",
    kurz: "Für eine Spritze kontrolliere ich möglichst zwei Farben und habe berechtigte Hoffnung auf vier Stiche.",
    lang:
      "Fünf Trümpfe, darunter zwei Ober und ein Schmiertrumpf, dazu eine zweite freie Farbe — das ist der Zuschnitt, mit dem sich eine Spritze rechnet. Es geht nicht um ein gutes Gefühl, sondern um vier Stiche im Schnitt. Mit weniger übernimmt man die Spielmacherrolle, ohne die Karten dafür zu haben.",
  },
  {
    id: "partner-zum-suchen-lassen",
    kapitel: "3.6",
    seite: 73,
    titel: "Den Partner zum Suchen kommen lassen",
    kurz: "Bin ich die Ruffarbe frei, lasse ich bevorzugt den Partner zum Stich kommen, damit er suchen kann.",
    lang:
      "Selbst kann ich die Rufsau nicht suchen — dafür brauche ich den Mitspieler am Ausspiel. Also nehme ich einen Trumpfstich nicht mit dem hohen Trumpf an mich, sondern gebe klein zu und überlasse den Stich der Hinterhand. Der hohe Trumpf bleibt für den Moment, in dem die Rufsau fällt.",
  },
  {
    id: "nicht-schwarz-werden",
    kapitel: "3.7",
    seite: 75,
    titel: "Nur nicht Schwarz werden",
    kurz: "Manchmal werfe ich den Schmiertrumpf ab und behalte den höchsten verbliebenen Trumpf, um nicht Schwarz zu werden.",
    lang:
      "Wenn das Spiel ohnehin verloren ist, geht es nur noch um Schneider und Schwarz. Ein Trumpf, der sicher einen Stich macht, ist dann mehr wert als die Augen darauf. Also gibt man die Punktkarte her und hält den Trumpf, der später wirklich sticht.",
  },
  {
    id: "schmieren-oder-stechen",
    kapitel: "3.8 / 3.9",
    seite: 77,
    titel: "Schmieren oder stechen — nur kein kleiner Trumpf",
    kurz: "Als Nichtspieler auf Platz 2 mit dem Partner auf Platz 4 gilt beim Anspiel eines hohen Trumpfes: stechen oder schmieren.",
    lang:
      "Spielt die Spielerpartei einen hohen Trumpf an und sitzt mein Partner hinter mir, ist ein kleiner Trumpf die schlechteste aller Karten: er gewinnt nichts und bringt nichts ein. Habe ich einen höheren Ober, übersteche ich. Habe ich keinen, schmiere ich die Trumpf-Sau — mein Partner sitzt hinten und kann den Stich noch holen.",
  },
  {
    id: "hohen-trumpf-opfern",
    kapitel: "3.10",
    seite: 81,
    titel: "Den richtigen Trumpf abgeben",
    kurz: "Manchmal opfere ich einen hohen Trumpf, um mir den Schmiertrumpf für den Partner zu erhalten.",
    lang:
      "Wenn ich auf einen großen Ober ohnehin nichts ausrichte, entscheidet nur noch, was ich behalte. Ein hoher Trumpf, der später doch überstochen wird, nützt weniger als eine Punktkarte, die ich dem Partner in einen sicheren Stich geben kann. Also gebe ich den Ober her und behalte den Schmiertrumpf.",
  },
  {
    id: "stechen-oder-unterstehen",
    kapitel: "3.11",
    seite: 83,
    titel: "Stechen oder unterstehen",
    kurz: "Ich steche, weil ich will — nicht, weil ich kann.",
    lang:
      "Mit dem Alten zu übernehmen lohnt, wenn ich drei oder mehr Karten der Ruffarbe habe und danach suchen kann, oder wenn ein Schmiertrumpf im Stich liegt. Unterstehen ist besser, wenn wenig Augen liegen und ich für den Alten später mehr erwarte, wenn ich nach dem Stechen gar nicht suchen könnte, wenn ich eine freie Farbe habe, die der Partner anspielen soll, oder wenn ich unsere Partei einfach in Hinterhand halten will.",
  },
  {
    id: "spritze-nach-farbanspiel",
    kapitel: "3.12",
    seite: 85,
    titel: "Spritze nach Anspiel einer freien Farbe",
    kurz: "Zwei absehbare punktreiche Farbstiche und ein sicherer Trumpfstich reichen für eine Spritze.",
    lang:
      "Eröffnet jemand mit einer Farbe, ohne zu suchen, und ich bin diese Farbe frei, kann ich mit einem hohen Ober sofort den Stich machen und anschließend selbst suchen. Rechne ich zwei punktreiche Farbstiche zusammen, steht der Punktestand schon vor dem eigentlichen Kampf gut — dann ist die Spritze kein Wagnis mehr, sondern Rechnung.",
  },
  {
    id: "trumpfstich-sichern",
    kapitel: "3.13",
    seite: 87,
    titel: "Einen Trumpfstich sichern",
    kurz: "Um keinen Trumpfstich zu verschenken, gehe ich notfalls von der ungünstigsten Trumpfverteilung aus.",
    lang:
      "Wenn ich einen Stich ohnehin nicht halten kann, ist die Frage nur, welchen Trumpf ich einsetze. Der kleinste ist verlockend — aber wenn die großen Ober beim Spielmacher stehen, nimmt er mir danach beide kleineren ab. Setze ich stattdessen den mittleren ein, bleibt mir ein Trumpf, der später wirklich sticht.",
  },
  {
    id: "zweite-hand-gibt-nichts",
    kapitel: "3.14",
    seite: 89,
    titel: "In zweiter Hand nichts geben",
    kurz: "Auf einen angespielten Schmiertrumpf gilt an Position 2 mit dem Partner an Position 4: die zweite Hand gibt nichts.",
    lang:
      "Die elf Augen der Trumpf-Sau absichern zu wollen ist verständlich und meist falsch. Der Spielmacher sitzt hinter mir; jeder hohe Trumpf, den ich jetzt einsetze, wird von ihm überstochen und ist verschenkt. Mein Partner in Hinterhand kann den Stich noch holen — ich gebe klein zu und provoziere gar nichts.",
  },
  {
    id: "truempfe-rechtzeitig",
    kapitel: "3.15",
    seite: 91,
    titel: "Trümpfe nicht zu lange zurückhalten",
    kurz: "Als starker Gegenspieler setze ich meine Trümpfe rechtzeitig ein statt auf das große Finale zu warten.",
    lang:
      "Der Gedanke, die hohen Ober für den fetten Stich am Ende aufzuheben, kostet regelmäßig Spiele. Steche ich früh ein, komme ich ans Ausspiel, kann die Rufsau suchen und meine freie Farbe bringen — und mein Partner sticht dort vielleicht noch ein. Wer wartet, hat am Ende die besten Trümpfe und keine Gelegenheit mehr.",
  },
  {
    id: "zehn-statt-sau",
    kapitel: "3.16",
    seite: 93,
    titel: "Zehn statt Sau spielen",
    kurz: "Mit Sau und Zehn einer Farbe spiele ich die Zehn — der erste Gegner rätselt dann, wer die Sau hat.",
    lang:
      "Halte ich Sau und Zehn und müssen beide Gegner noch zugeben, verleitet die gespielte Zehn den ersten dazu, den zweiten für den Besitzer der Sau zu halten. Statt einzustechen wirft er womöglich einen Spatz ab — und meine Sau macht den Stich später trotzdem.",
  },
  {
    id: "zwei-fehlkarten-vermuten",
    kapitel: "3.17",
    seite: 95,
    titel: "Zwei gleichfarbige Fehlkarten vermuten",
    kurz: "Nicht selten hat der Spielmacher im Sauspiel zwei Fehlkarten derselben Farbe.",
    lang:
      "Wirft der Spielmacher in einer Farbe einen Spatz ab, ist er dort selten blank. Die zweite Karte derselben Farbe kommt meist noch. Wer damit rechnet, spielt die Farbe ein zweites Mal an, statt sie für erledigt zu halten — und trifft ihn dort noch einmal.",
  },
  {
    id: "partner-uebertsechen",
    kapitel: "3.18",
    seite: 97,
    titel: "Den eigenen Partner überstechen",
    kurz: "Manchmal übersteche ich bewusst den Partner, um sofort suchen zu können oder ihn in Hinterhand zu bringen.",
    lang:
      "Eröffnet der Partner mit einer Farb-Sau und sucht nicht, ist er diese Farbe vermutlich frei. Steche ich über, komme ich ans Ausspiel und kann selbst die Rufsau suchen — und er sitzt danach hinter dem Spielmacher. Das sieht nach Verrat aus und ist Zusammenspiel.",
  },
  {
    id: "blanker-alter-eroeffnung",
    kapitel: "3.19",
    seite: 99,
    titel: "Als Nichtspieler mit dem Alten eröffnen",
    kurz: "Ein blank ausgespielter Eichel-Ober gewinnt das Vertrauen des Spielmachers — die nachgespielte Sau sticht er dann oft nicht.",
    lang:
      "Wer den Alten anspielt, gilt am Tisch als der gerufene Partner: so eröffnet niemand als Gegenspieler. Der Spielmacher hält dich für seinen Freund und lässt deine nachgespielte Farb-Sau womöglich durchgehen, statt sie zu stechen. Eine Finte, die man dezent und selten einsetzt.",
  },
  {
    id: "schmierkarte-opfern",
    kapitel: "3.20",
    seite: 101,
    titel: "Dem Gegner eine Schmierkarte überlassen",
    kurz: "Ich opfere eine Schmierkarte oder verzichte auf einen Stich, wenn ich dafür später einen wertvolleren gewinne.",
    lang:
      "Sofort einzustechen bringt oft nur ein paar Augen und kostet einen Trumpf. Wirf stattdessen die einzeln stehende Farbkarte ab: die Trumpfstiche bleiben dir alle erhalten, und du bist eine zweite Farbe frei, in der du später einstechen kannst. Rechne den Stich gegen das, was danach möglich wird.",
  },
  {
    id: "rufsau-nicht-stechen",
    kapitel: "3.21",
    seite: 103,
    titel: "Die Rufsau auch einmal nicht stechen",
    kurz: "Ich steche, weil ich will und nicht, weil ich kann — das gilt auch für die Rufsau.",
    lang:
      "Die Rufsau zu rauben ist die schönste Pflicht des Gegenspielers und trotzdem nicht immer richtig. Mit fünf guten Trümpfen und mehreren freien Farben bist du der starke Gegenspieler: stichst du mechanisch, gibst du eine Lusche her, die du zum Abwerfen gebraucht hättest, und verlierst die Kontrolle über die Farben. Elf Augen sind es nicht wert.",
  },
  {
    id: "trumpf-nach-davonlaufen",
    kapitel: "3.22",
    seite: 105,
    titel: "Trumpf spielen, wenn der Gegner davongelaufen ist",
    kurz: "Um dem Davongelaufenen nicht in eine freie Farbe zu spielen, bringe ich als Nichtspieler auch einmal Trumpf.",
    lang:
      "Wer davonläuft, hält mindestens vier Karten der Ruffarbe und ist deshalb in einer der beiden anderen Farben oft frei. Spielst du dort hinein, sticht er ein. Trumpf ist die Farbe, in der er dir nichts wegnehmen kann — und du entlastest deine eigenen Sauen.",
  },
  {
    id: "trostlos-ungewoehnlich",
    kapitel: "3.23",
    seite: 107,
    titel: "Mit trostlosen Karten etwas Ungewöhnliches",
    kurz: "Gerade mit hoffnungslosen Karten verstoße ich hin und wieder gegen die Routine.",
    lang:
      "Mit einer einzeln stehenden Ruffarbkarte routinemäßig zu suchen führt hier nur dazu, dass du den nächsten hohen Trumpf auch noch bedienen musst. Spiel stattdessen den blanken Schmiertrumpf an: unangenehm für den Spielmacher, und dein Partner sitzt direkt hinter ihm. Wo nichts zu verlieren ist, ist Routine das größte Risiko.",
  },
  {
    id: "farbe-wiederholt-anspielen",
    kapitel: "3.24",
    seite: 109,
    titel: "Die Rufsau einmal nicht suchen",
    kurz: "Durch wiederholtes Anspielen derselben Farbe ziehe ich dem Spielmacher mehrere, auch hohe Trümpfe.",
    lang:
      "Statt zu suchen spielst du die Farbe an, in der du selbst lang bist und der Spielmacher vermutlich frei. Er muss stechen, und zwar besser hoch, sonst übernimmt dein Partner. Spielst du dieselbe Farbe zwei- und dreimal, kostet ihn das jedes Mal einen Trumpf — mehr, als das Suchen je gebracht hätte.",
  },
];

/* Sitze: 1 = Vorhand, dann im Uhrzeigersinn 2, 3, 4.
   „ich" ist der Sitz des Lernenden, „spielmacher" der Ansager. */

export const STELLUNGEN = [
  {
    id: "b2-2.6-s48",
    regelId: "freie-farbe-anzeigen",
    seite: 48,
    spiel: { type: "sauspiel", suit: "E" },
    rolle: "gerufener Partner",
    ich: 4,
    spielmacher: 2,
    lage: "Erster Stich: die Ruffarbe wurde gesucht, du hast mit der Eichel-Sau gestochen und spielst nach.",
    stich: [
      { sitz: 1, card: "E7" }, { sitz: 2, card: "EX" }, { sitz: 3, card: "E8" }, { sitz: 4, card: "EA" },
    ],
    hand: ["GO", "HX", "H7", "E9", "GK", "G9", "G7"],
    frage: "Welche Karte soll ich nachspielen?",
    loesung: ["GK", "G9", "G7"],
    loesungstext: "Eine Gras-Karte, zum Beispiel den Gras-König",
    begruendung:
      "Mit drei kleinen Trümpfen hilft Trumpf ziehen dem Spielmacher nicht. Spielst du Gras — also die dritte Farbe —, zeigst du ihm damit an, dass du Schellen frei bist und dort einstechen kannst.",
  },
  {
    id: "b2-2.7-s50",
    regelId: "nicht-immer-hoechster-trumpf",
    seite: 50,
    spiel: { type: "sauspiel", suit: "E" },
    rolle: "gerufener Partner",
    ich: 1,
    spielmacher: 2,
    lage: "Du bist in Vorhand, der Spielmacher sitzt in Mittelhand.",
    stich: [],
    hand: ["SO", "H8", "H7", "EA", "GX", "G9", "S8", "S7"],
    frage: "Welche Karte soll ich ausspielen?",
    loesung: ["H7"],
    loesungstext: "Die Herz-Sieben",
    begruendung:
      "Der Schellen-Ober ist hoch, aber keiner der drei großen Ober. Spielst du ihn an, kann der Spielmacher in Mittelhand ihn nur mit einem großen Ober übernehmen — oder er lässt ihn, und die Hinterhand schmiert. Der kleine Trumpf zwingt ihn dagegen, selbst Farbe zu bekennen, und du behältst den Ober für später.",
  },
  {
    id: "b2-2.8-s52",
    regelId: "ohne-trumpf-rufsau-spielen",
    seite: 52,
    spiel: { type: "sauspiel", suit: "E" },
    rolle: "gerufener Partner",
    ich: 1,
    spielmacher: 2,
    lage: "Du bist in Vorhand und hast keinen einzigen Trumpf.",
    stich: [],
    hand: ["EA", "EK", "E7", "GA", "GK", "G8", "G7", "SA"],
    frage: "Welche Karte soll ich ausspielen?",
    loesung: ["EA"],
    loesungstext: "Die Eichel-Sau",
    begruendung:
      "Ohne Trumpf kannst du dich nicht durch Trumpfspielen zeigen, und mit nur drei Eichel-Karten darfst du nicht davonlaufen. Bleibt die Rufsau selbst. Sie wird wahrscheinlich gestochen — trotzdem richtig: der Spielmacher muss wissen, dass er allein Trumpf ziehen muss.",
  },
  {
    id: "b2-2.9-s54",
    regelId: "nicht-davonlaufen-nach-abspatzen",
    seite: 54,
    spiel: { type: "sauspiel", suit: "E" },
    rolle: "gerufener Partner",
    ich: 2,
    spielmacher: 3,
    lage:
      "Ein Gegner hat Schellen angespielt, du hast mit der Herz-Sieben gestochen. Der Spielmacher hat dabei nicht eingestochen, sondern die Eichel-Acht abgeworfen. Du hältst die Rufsau und vier Eichel-Karten — davonlaufen wäre erlaubt.",
    stich: [],
    hand: ["HU", "H8", "EA", "EX", "EK", "E9", "G8"],
    frage: "Soll ich davonlaufen?",
    loesung: ["HU", "H8"],
    loesungstext: "Nein — lieber Trumpf spielen",
    begruendung:
      "Dass der Spielmacher eine Eichel-Lusche abwirft, statt auf Schellen einzustechen, heißt: er ist selbst schellenfrei und will Eichel loswerden. Läufst du davon, bekommt er genau die Gelegenheit dazu. Trumpf nimmt den Gegnern stattdessen die Möglichkeit, deine Eichel abzustechen.",
  },
  {
    id: "b2-2.10-s56",
    regelId: "nach-spritze-rollen-tauschen",
    seite: 56,
    spiel: { type: "sauspiel", suit: "E" },
    rolle: "gerufener Partner",
    ich: 1,
    spielmacher: 2,
    lage: "Der Gegenspieler auf Position 4 hat gespritzt. Du bist in Vorhand und hältst die Rufsau.",
    stich: [],
    hand: ["HU", "H8", "EA", "EK", "E8", "GX", "G8", "SK"],
    frage: "Welche Karte soll ich ausspielen?",
    loesung: ["SK"],
    loesungstext: "Keinen Trumpf, sondern eine Farbe — hier den blanken Schellen-König",
    begruendung:
      "Wer spritzt, hat meist mindestens so viel Trumpf wie der Spielmacher. Also verhältst du dich ab jetzt wie ein Nichtspieler: kein Trumpf, sondern Farbe, und zwar am liebsten die blanke Karte — dann kannst du später selbst einstechen.",
  },
  {
    id: "b2-2.11-s58",
    regelId: "vorausdenken-ausspiel",
    seite: 58,
    spiel: { type: "sauspiel", suit: "E" },
    rolle: "gerufener Partner",
    ich: 2,
    spielmacher: 1,
    lage: "Der Spielmacher kommt mit dem Herz-Ober heraus. Du sitzt direkt hinter ihm und hältst die Rufsau.",
    stich: [{ sitz: 1, card: "HO" }],
    hand: ["EO", "H7", "EA", "E8", "E7", "GA", "G7", "SK"],
    frage: "Welchen Trumpf soll ich zugeben?",
    loesung: ["EO"],
    loesungstext: "Den Eichel-Ober",
    begruendung:
      "Die Herz-Sieben wäre der Reflex. Aber dann bleibt der Spielmacher am Ausspiel und kommt womöglich mit dem Schellen-Ober nach — den müsstest du mit dem Alten überstechen und hättest ihn für nichts verbraucht. Überstichst du gleich jetzt, bist du selbst am Ausspiel und kannst deine Gras-Sau bringen.",
  },
  {
    id: "b2-3.1-s62",
    regelId: "blanke-zehn-suchen",
    seite: 62,
    spiel: { type: "sauspiel", suit: "E" },
    rolle: "Gegenspieler",
    ich: 1,
    spielmacher: 3,
    lage: "Du bist Gegenspieler in Vorhand. Von der Ruffarbe hast du nur die blanke Eichel-Zehn.",
    stich: [],
    hand: ["GO", "GU", "HK", "EX", "GA", "G7", "SK", "S9"],
    frage: "Soll ich mit der blanken Zehn suchen?",
    loesung: ["EX"],
    loesungstext: "Eher schon — die Eichel-Zehn",
    begruendung:
      "Die Zehn geht dabei oft verloren, aber du erfährst sofort, wer der Partner ist, und der Spielmacher verliert die Kontrolle über die Ruffarbe. Dass ausgerechnet er dort frei ist, ist unwahrscheinlich.",
  },
  {
    id: "b2-3.2-s64",
    regelId: "dreifach-besetzte-zehn",
    seite: 64,
    spiel: { type: "sauspiel", suit: "E" },
    rolle: "Gegenspieler",
    ich: 1,
    spielmacher: 3,
    lage: "Du bist Gegenspieler in Vorhand und hältst drei Eichel-Karten — Zehn, König und Sieben. Trumpf hast du nur einen.",
    stich: [],
    hand: ["EU", "EX", "EK", "E7", "GK", "G7", "SX", "S7"],
    frage: "Mit welcher Karte soll ich suchen?",
    loesung: ["EK"],
    loesungstext: "Mit dem Eichel-König",
    begruendung:
      "Bei drei Eichel-Karten steht der Spielmacher gut die Hälfte der Fälle frei und sticht. Die Zehn wäre dann weg. Der König sucht genauso gut, und die Zehn bleibt für die sicheren Stiche des Partners — Schmierkarten hast du sonst kaum.",
  },
  {
    id: "b2-3.3-s66",
    regelId: "nicht-suchen-ohne-partnertrumpf",
    seite: 66,
    spiel: { type: "sauspiel", suit: "E" },
    rolle: "Gegenspieler",
    ich: 3,
    spielmacher: 1,
    lage:
      "Der Spielmacher kam mit dem Gras-Ober, du hast mit dem Eichel-Ober überstochen. Dein Hintermann gab die Gras-Zehn zu, der Vierte den Herz-König — dein Partner hat also keinen Trumpf mehr. Du bist am Ausspiel.",
    stich: [],
    hand: ["EU", "HU", "H8", "H7", "EX", "EK", "S7"],
    frage: "Welche Karte soll ich ausspielen?",
    loesung: ["S7"],
    loesungstext: "Die Schellen-Sieben",
    begruendung:
      "Routinemäßig zu suchen wäre hier falsch: dein Partner kann nicht einstechen, die Eichel-Zehn ginge an die Spielerpartei. Spiel stattdessen Schellen — dort bist du grasfrei und kannst später selbst noch stechen.",
  },
  {
    id: "b2-3.4-s68",
    regelId: "anspiel-farbe-ohne-sau",
    seite: 68,
    spiel: { type: "sauspiel", suit: "E" },
    rolle: "Gegenspieler",
    ich: 1,
    spielmacher: 3,
    lage: "Du bist Gegenspieler in Vorhand und hast keine einzige Karte der Ruffarbe.",
    stich: [],
    hand: ["GO", "GU", "HK", "H7", "GK", "G7", "SA", "S7"],
    frage: "Welche Karte soll ich ausspielen?",
    loesung: ["GK", "G7"],
    loesungstext: "Den Gras-König oder die Gras-Sieben — nicht die Schellen-Sau",
    begruendung:
      "Die Rufsau zu stechen ist dein wichtigstes Ziel, aber suchen kannst du nicht selbst. Also gibst du das Ausspiel weiter, und zwar in der Farbe ohne eigene Sau. Die Schellen-Sau willst du später selbst einbringen, nicht verschenken.",
  },
  {
    id: "b2-3.5-s70",
    regelId: "spritze-voraussetzung",
    seite: 70,
    spiel: { type: "sauspiel", suit: "E" },
    rolle: "Gegenspieler",
    ich: 2,
    spielmacher: 1,
    lage: "Fünf Trümpfe, darunter zwei Ober und der Herz-Zehner. Eichel und Schellen bist du frei.",
    stich: [],
    hand: ["GO", "SO", "SU", "HX", "H8", "GK", "G9", "G7"],
    frage: "Soll ich eine Spritze geben?",
    optionen: ["Ja", "Nein"],
    loesung: ["Ja"],
    loesungstext: "Ja",
    begruendung:
      "Genau dieser Zuschnitt rechtfertigt eine Spritze: fünf Trümpfe mit zwei Obern, ein Schmiertrumpf und zwei kontrollierte Farben — darunter die Ruffarbe. Vier Stiche sind realistisch. Wenn nicht hier, wann dann?",
  },
  {
    id: "b2-3.6-s72",
    regelId: "partner-zum-suchen-lassen",
    seite: 72,
    spiel: { type: "sauspiel", suit: "E" },
    rolle: "Gegenspieler",
    ich: 3,
    spielmacher: 2,
    lage:
      "Spieler 1 spielt Trumpf an und gibt sich damit als Freund des Spielmachers zu erkennen — dein Hintermann gehört also zu dir. Du bist die Ruffarbe frei und hast nur zwei Trümpfe.",
    stich: [{ sitz: 1, card: "GU" }, { sitz: 2, card: "HK" }],
    hand: ["GO", "H7", "GX", "GK", "G7", "SK", "S9", "S7"],
    frage: "Welchen Trumpf soll ich zugeben?",
    loesung: ["H7"],
    loesungstext: "Die Herz-Sieben",
    begruendung:
      "Mit dem Gras-Ober würdest du den Stich an dich reißen — und danach die Rufsau nicht suchen können, weil du eichelfrei bist. Gib klein zu und lass den Hintermann zum Stich kommen: er sucht, du stichst später mit dem Ober.",
  },
  {
    id: "b2-3.7-s74",
    regelId: "nicht-schwarz-werden",
    seite: 74,
    spiel: { type: "sauspiel", suit: "E" },
    rolle: "Gegenspieler",
    ich: 4,
    spielmacher: 1,
    lage:
      "Der Spielmacher kommt mit dem Eichel-Ober, Spieler 2 schmiert den Herz-Zehner und zeigt sich damit als sein Partner. Spieler 3 gibt den Eichel-Unter zu. Du hast nur zwei Trümpfe.",
    stich: [{ sitz: 1, card: "EO" }, { sitz: 2, card: "HX" }, { sitz: 3, card: "EU" }],
    hand: ["GO", "HA", "E9", "E8", "GA", "G9", "G7", "SX"],
    frage: "Welche Karte soll ich zugeben?",
    loesung: ["HA"],
    loesungstext: "Die Herz-Sau",
    begruendung:
      "Das Spiel ist kaum noch zu gewinnen — jetzt geht es um Schneider und Schwarz. Der Gras-Ober ist dein sicherer Stich und den behältst du. Die Herz-Sau gibst du her: elf Augen, die dir sonst nichts nützen, gegen einen Stich, der zählt.",
  },
  {
    id: "b2-3.8-s76",
    regelId: "schmieren-oder-stechen",
    seite: 76,
    spiel: { type: "sauspiel", suit: "E" },
    rolle: "Gegenspieler",
    ich: 2,
    spielmacher: 3,
    lage:
      "Der gerufene Partner auf Platz 1 spielt seinen höchsten Trumpf an, den Herz-Ober. Dein eigener Partner sitzt auf Platz 4, hinter allen. Dein höchster Trumpf ist der Schellen-Ober.",
    stich: [{ sitz: 1, card: "HO" }],
    hand: ["SO", "HA", "H7", "E9", "GX", "G9", "SA", "SK"],
    frage: "Welche Karte soll ich zugeben?",
    loesung: ["HA"],
    loesungstext: "Die Herz-Sau",
    begruendung:
      "Übersteechen kannst du den Herz-Ober nicht — der Schellen-Ober ist kleiner. Ein kleiner Trumpf brächte gar nichts. Also schmierst du die Trumpf-Sau: dein Partner sitzt hinten und kann den Stich noch holen.",
  },
  {
    id: "b2-3.9-s78",
    regelId: "schmieren-oder-stechen",
    seite: 78,
    spiel: { type: "sauspiel", suit: "E" },
    rolle: "Gegenspieler",
    ich: 2,
    spielmacher: 3,
    lage:
      "Dieselbe Lage wie zuvor — nur hältst du diesmal statt des Schellen-Obers den Gras-Ober. Der gerufene Partner auf Platz 1 kommt mit dem Herz-Ober.",
    stich: [{ sitz: 1, card: "HO" }],
    hand: ["GO", "HA", "H7", "EK", "E7", "GA", "S9", "S7"],
    frage: "Welchen Trumpf soll ich zugeben?",
    loesung: ["GO"],
    loesungstext: "Den Gras-Ober",
    begruendung:
      "Diesmal kannst du überstechen — und das ist mehr wert als die geschmierte Sau. Der Alte sitzt beim Spielmacher hinter dir; die Herz-Sau würde er wegstechen. Mit dem Gras-Ober nimmst du den Stich selbst und kommst ans Ausspiel.",
  },
  {
    id: "b2-3.10-s80",
    regelId: "hohen-trumpf-opfern",
    seite: 80,
    spiel: { type: "sauspiel", suit: "E" },
    rolle: "Gegenspieler",
    ich: 2,
    spielmacher: 1,
    lage: "Der Spielmacher kommt mit dem Eichel-Ober. Du hast genau zwei Trümpfe: den Herz-Ober und den Herz-Zehner.",
    stich: [{ sitz: 1, card: "EO" }],
    hand: ["HO", "HX", "EX", "EK", "GX", "GK", "SA", "S7"],
    frage: "Welchen Trumpf soll ich zugeben?",
    loesung: ["HO"],
    loesungstext: "Den Herz-Ober",
    begruendung:
      "Es tut weh, ist aber richtig. Der Herz-Ober wird im Lauf des Spiels ohnehin überstochen. Die Herz-Zehn dagegen kannst du deinem Partner in einen sicheren Stich schmieren — das sind zusätzliche zehn Augen. Und solange ihr keinen Stich habt, geht es auch darum, nicht Schwarz zu werden.",
  },
  {
    id: "b2-3.11-s82",
    regelId: "stechen-oder-unterstehen",
    seite: 82,
    spiel: { type: "sauspiel", suit: "E" },
    rolle: "Gegenspieler",
    ich: 4,
    spielmacher: 2,
    lage: "Der Gras-Ober ist angespielt, es liegen kaum Augen im Stich. Du hältst den Alten und den Schellen-Ober.",
    stich: [{ sitz: 1, card: "GO" }, { sitz: 2, card: "H9" }, { sitz: 3, card: "H7" }],
    hand: ["EO", "SO", "GU", "HK", "EK", "GX", "G7", "SA"],
    frage: "Welchen Trumpf soll ich zugeben?",
    loesung: ["HK"],
    loesungstext: "Den Herz-König",
    begruendung:
      "Übernehmen könntest du — aber wozu? Im Stich liegen kaum Augen, und für den Alten bekommst du später deutlich mehr. Du hast nur eine Eichel-Karte, könntest nach dem Stechen also nicht sinnvoll suchen. Unterstehen hält euch obendrein in Hinterhand.",
  },
  {
    id: "b2-3.12-s84",
    regelId: "spritze-nach-farbanspiel",
    seite: 84,
    spiel: { type: "sauspiel", suit: "E" },
    rolle: "Gegenspieler",
    ich: 4,
    spielmacher: 2,
    lage: "Spieler 1 eröffnet mit dem Schellen-Zehner, sucht also nicht. Du bist schellenfrei und hältst den Alten, den Schellen-Ober und drei Eichel-Karten.",
    stich: [{ sitz: 1, card: "SX" }],
    hand: ["EO", "SO", "HK", "EX", "E8", "E7", "GX", "G7"],
    frage: "Soll ich eine Spritze geben?",
    optionen: ["Ja", "Nein"],
    loesung: ["Ja"],
    loesungstext: "Ja",
    begruendung:
      "Mit dem Alten machst du diesen Stich sicher, danach suchst du selbst mit der Eichel-Zehn. Zwei punktreiche Farbstiche gleich zu Beginn plus ein sicherer Trumpfstich — mehr braucht eine Spritze nicht.",
  },
  {
    id: "b2-3.13-s86",
    regelId: "trumpfstich-sichern",
    seite: 86,
    spiel: { type: "sauspiel", suit: "E" },
    rolle: "Gegenspieler",
    ich: 3,
    spielmacher: 4,
    lage: "Die Trumpf-Sau ist angespielt, der Herz-Unter liegt drauf. Der Spielmacher sitzt hinter dir und lässt sich den Stich nicht entgehen.",
    stich: [{ sitz: 1, card: "HA" }, { sitz: 2, card: "HU" }],
    hand: ["HO", "SO", "GU", "E7", "GX", "SA", "SK", "S8"],
    frage: "Welchen Trumpf soll ich zugeben?",
    loesung: ["SO"],
    loesungstext: "Den Schellen-Ober, nicht den Gras-Unter",
    begruendung:
      "Den Stich hältst du nicht. Gibst du nur den Gras-Unter, übernimmt der Spielmacher mit dem Eichel-Unter und nimmt dir danach mit seinen großen Obern auch noch die beiden kleineren Trümpfe ab. Rechne mit der ungünstigsten Verteilung: setz den Schellen-Ober ein, dann bleibt dir der Herz-Ober für einen echten Stich.",
  },
  {
    id: "b2-3.14-s88",
    regelId: "zweite-hand-gibt-nichts",
    seite: 88,
    spiel: { type: "sauspiel", suit: "E" },
    rolle: "Gegenspieler",
    ich: 2,
    spielmacher: 3,
    lage: "Die Trumpf-Sau ist angespielt. Der Spielmacher sitzt direkt hinter dir, dein Partner auf Platz 4.",
    stich: [{ sitz: 1, card: "HA" }],
    hand: ["GO", "EU", "HX", "H7", "EX", "E7", "GK", "G7"],
    frage: "Welchen Trumpf soll ich zugeben?",
    loesung: ["H7"],
    loesungstext: "Die Herz-Sieben, nicht den Gras-Ober",
    begruendung:
      "Die elf Augen absichern zu wollen ist der falsche Reflex: der Spielmacher sitzt hinter dir und übersticht den Gras-Ober mit dem Alten. Dein Partner in Hinterhand kann den Stich noch holen. Die zweite Hand gibt nichts.",
  },
  {
    id: "b2-3.15-s90",
    regelId: "truempfe-rechtzeitig",
    seite: 90,
    spiel: { type: "sauspiel", suit: "E" },
    rolle: "Gegenspieler",
    ich: 4,
    spielmacher: 1,
    lage: "Der Spielmacher zieht Trumpf mit dem Herz-Ober, es liegen wenige Augen im Stich. Du bist der starke Gegenspieler mit fünf Trümpfen und bist Gras frei.",
    stich: [{ sitz: 1, card: "HO" }, { sitz: 2, card: "SU" }, { sitz: 3, card: "H8" }],
    hand: ["EO", "GO", "HX", "H9", "H7", "EK", "E8", "SK"],
    frage: "Welchen Trumpf soll ich zugeben?",
    loesung: ["GO"],
    loesungstext: "Den Gras-Ober",
    begruendung:
      "Auch wenn wenig liegt: steche jetzt ein. Damit kommst du ans Ausspiel, kannst die Rufsau suchen und später deine freie Farbe Gras bringen — dort sticht dein Partner vielleicht ein. Wer die Ober fürs große Finale aufhebt, riskiert, mit ihnen gar nicht mehr zum Zug zu kommen.",
  },
  {
    id: "b2-3.16-s92",
    regelId: "zehn-statt-sau",
    seite: 92,
    spiel: { type: "sauspiel", suit: "E" },
    rolle: "Gegenspieler",
    ich: 4,
    spielmacher: 1,
    lage:
      "Im ersten Stich hat Spieler 3 den Herz-Ober des Spielmachers überstochen — dein Partner. Du hast ihn mit dem Herz-Zehner belohnt. Jetzt spielt er die Schellen-Acht, und du hältst Sau, Zehn und Sieben in Schellen.",
    stich: [{ sitz: 3, card: "S8" }],
    hand: ["HU", "SA", "SX", "S7", "EK", "E8", "GK"],
    frage: "Welche Karte soll ich zugeben?",
    loesung: ["SX"],
    loesungstext: "Die Schellen-Zehn",
    begruendung:
      "Beide Gegner müssen noch zugeben. Spielst du die Zehn statt der Sau, hält der erste den zweiten für den Besitzer der Sau — statt einzustechen wirft er womöglich einen Spatz ab. Deine Sau macht den Stich später trotzdem.",
  },
  {
    id: "b2-3.17-s94",
    regelId: "zwei-fehlkarten-vermuten",
    seite: 94,
    spiel: { type: "sauspiel", suit: "E" },
    rolle: "Gegenspieler",
    ich: 3,
    spielmacher: 4,
    lage:
      "In der ersten Runde hat der Ausspieler mit der Gras-Sau einen Spatz des Spielmachers erwischt. Nun kommt die nächste Gras-Karte, der Schellen-Unter liegt schon drauf.",
    stich: [{ sitz: 1, card: "GX" }, { sitz: 2, card: "SU" }],
    hand: ["EO", "HU", "H7", "EK", "E7", "SX", "SK"],
    frage: "Welche Karte soll ich spielen?",
    loesung: ["HU"],
    loesungstext: "Den Herz-Unter",
    begruendung:
      "Der Spielmacher hat in Gras selten nur eine Karte gehabt — rechne mit einer zweiten. Mit dem Herz-Unter stichst du, ohne den Alten zu vergeuden, und kommst ans Ausspiel. Den Alten hebst du auf, um damit später den Blauen zu erwischen.",
  },
  {
    id: "b2-3.18-s96",
    regelId: "partner-uebertsechen",
    seite: 96,
    spiel: { type: "sauspiel", suit: "E" },
    rolle: "Gegenspieler",
    ich: 4,
    spielmacher: 3,
    lage: "Spieler 1 eröffnet mit der Gras-Sau und sucht nicht — vermutlich dein Partner, und vermutlich eichelfrei. Du bist eichelfrei nicht, hast aber Trumpf.",
    stich: [{ sitz: 1, card: "GA" }, { sitz: 2, card: "GX" }, { sitz: 3, card: "G9" }],
    hand: ["SO", "SU", "HK", "H7", "EK", "E9", "SX", "S9"],
    frage: "Soll ich schmieren oder stechen?",
    loesung: ["HK", "H7"],
    loesungstext: "Stechen, zum Beispiel mit dem Herz-König",
    begruendung:
      "Den eigenen Partner zu überstechen sieht falsch aus und ist hier richtig: du kommst ans Ausspiel, kannst selbst die Rufsau suchen, und dein Partner sitzt danach in Hinterhand. Nimm dafür einen kleinen Trumpf, nicht den Ober.",
  },
  {
    id: "b2-3.19-s98",
    regelId: "blanker-alter-eroeffnung",
    seite: 98,
    spiel: { type: "sauspiel", suit: "E" },
    rolle: "Gegenspieler",
    ich: 1,
    spielmacher: 2,
    lage: "Du bist Gegenspieler in Vorhand. Dein einziger Trumpf ist der Eichel-Ober, dazu hast du vier Gras-Karten mit der Sau.",
    stich: [],
    hand: ["EO", "EK", "GA", "GK", "G9", "G7", "SK", "S7"],
    frage: "Welche Karte soll ich ausspielen?",
    loesung: ["EO"],
    loesungstext: "Den Eichel-Ober",
    begruendung:
      "Routinemäßig mit dem Eichel-König zu suchen bringt wenig. Spiel stattdessen den blanken Alten: so eröffnet nur der gerufene Partner. Der Spielmacher hält dich für seinen Freund und lässt deine Gras-Sau danach womöglich durchgehen.",
  },
  {
    id: "b2-3.20-s100",
    regelId: "schmierkarte-opfern",
    seite: 100,
    spiel: { type: "sauspiel", suit: "E" },
    rolle: "Gegenspieler",
    ich: 4,
    spielmacher: 2,
    lage: "Gras ist angespielt, du bist grasfrei. Mit vier Trümpfen kommst du im Lauf des Spiels etwa dreimal zum Stechen — und hältst eine einzelne Schellen-Zehn.",
    stich: [{ sitz: 1, card: "G9" }, { sitz: 2, card: "GK" }, { sitz: 3, card: "G7" }],
    hand: ["EO", "SO", "GU", "H9", "EX", "E9", "E7", "SX"],
    frage: "Welche Karte soll ich spielen?",
    loesung: ["SX"],
    loesungstext: "Die Schellen-Zehn",
    begruendung:
      "Sofort einzustechen bringt vier Augen und kostet einen Trumpf — danach bleiben dir nur zwei sichere Trumpfstiche. Gibst du die einzelne Schellen-Zehn ab, behältst du alle drei und bist ab sofort eine zweite Farbe frei.",
  },
  {
    id: "b2-3.21-s102",
    regelId: "rufsau-nicht-stechen",
    seite: 102,
    spiel: { type: "sauspiel", suit: "E" },
    rolle: "Gegenspieler",
    ich: 4,
    spielmacher: 3,
    lage: "Die Rufsau ist gefallen und du könntest sie mit einem kleinen Trumpf holen. Du hast fünf gute Trümpfe und bist eichelfrei.",
    stich: [{ sitz: 1, card: "E7" }, { sitz: 2, card: "EA" }, { sitz: 3, card: "E8" }],
    hand: ["GO", "HO", "GU", "SU", "H9", "GA", "G7", "S9"],
    frage: "Welche Karte soll ich spielen?",
    loesung: ["S9"],
    loesungstext: "Die Schellen-Neun",
    begruendung:
      "Mit diesem Blatt hättest du selbst ein Sauspiel gemacht — du bist der starke Gegenspieler. Stichst du mechanisch, gibst du die Lusche her, die du zum Abwerfen brauchst, und verlierst die Kontrolle über die Farben. Elf Augen sind das nicht wert.",
  },
  {
    id: "b2-3.22-s104",
    regelId: "trumpf-nach-davonlaufen",
    seite: 104,
    spiel: { type: "sauspiel", suit: "E" },
    rolle: "Gegenspieler",
    ich: 3,
    spielmacher: 2,
    lage: "Der Ausspieler ist davongelaufen und hat sich damit als gerufener Partner gezeigt. Du hast den Stich mit dem Herz-Zehner geholt und bist am Ausspiel. In Gras und Schellen hältst du beide Sauen.",
    stich: [],
    hand: ["SO", "H8", "GA", "GK", "SA", "SK", "S9"],
    frage: "Welche Karte soll ich spielen?",
    loesung: ["SO"],
    loesungstext: "Den Schellen-Ober",
    begruendung:
      "Wer davonläuft, hat mindestens vier Karten der Ruffarbe und ist deshalb in Gras oder Schellen oft frei — genau dort stünden deine beiden Sauen. Trumpf ist die Farbe, in der er dir nichts nehmen kann, und zwingt den Spielmacher, einen hohen einzusetzen.",
  },
  {
    id: "b2-3.23-s106",
    regelId: "trostlos-ungewoehnlich",
    seite: 106,
    spiel: { type: "sauspiel", suit: "E" },
    rolle: "Gegenspieler",
    ich: 1,
    spielmacher: 2,
    lage: "Ein trostloses Blatt: ein einziger Trumpf, die blanke Herz-Zehn, dazu eine einzelne Eichel-Karte. Der Spielmacher sitzt direkt hinter dir.",
    stich: [],
    hand: ["HX", "EK", "GA", "GX", "G9", "SX", "SK", "S7"],
    frage: "Welche Karte soll ich ausspielen?",
    loesung: ["HX"],
    loesungstext: "Die Herz-Zehn",
    begruendung:
      "Suchst du mit der einzelnen Eichel-Karte, holt der Gegner seine Sau heim und kommt mit einem hohen Trumpf nach, den du mit der Zehn bedienen musst. Spiel den Schmiertrumpf lieber gleich selbst an: für den Spielmacher unangenehm, und dein Partner sitzt hinter ihm.",
  },
  {
    id: "b2-3.24-s108",
    regelId: "farbe-wiederholt-anspielen",
    seite: 108,
    spiel: { type: "sauspiel", suit: "E" },
    rolle: "Gegenspieler",
    ich: 1,
    spielmacher: 2,
    hinweis:
      "Im Buch zeigt die Abbildung an dieser Stelle den Gras-Zehner. Text und Lösung sprechen aber vom Gras-König, und auf Seite 109 heißt es, die Gras-Sau komme erst in der dritten Runde — sie liegt also ebenfalls auf der Hand. Hier steht deshalb der Gras-König.",
    lage:
      "Du bist Gegenspieler in Vorhand und hast nur zwei Trümpfe, dafür drei Gras-Karten. Der Spielmacher ist damit wahrscheinlich grasfrei.",
    stich: [],
    hand: ["EO", "HU", "GA", "GK", "G9", "E9", "SX", "SK"],
    frage: "Welche Karte soll ich ausspielen?",
    loesung: ["GK"],
    loesungstext: "Den Gras-König",
    begruendung:
      "Statt zu suchen spielst du Gras an — dort muss der Spielmacher stechen. Den König, nicht die Neun: bei der Neun wirft er einfach seinen Ruffarb-Spatz ab, beim König lohnt sich der Trumpf für ihn. Und nicht die Sau, die hebst du für die dritte Gras-Runde auf. Zweimal, dreimal Gras kostet ihn jedes Mal einen hohen Trumpf.",
  },
];

export const regelById = (id) => REGELN.find((r) => r.id === id) || null;
